default_template="elsevier"
templates={
  "elsevier":{
    "template_file":"templates/elsarticle-template-1-num.latex",
    "bibtexcommand":"bibtex",
    "natbib":"--natbib"
    },
  "scientific_reports":{
    "template_file":"templates/scientific_reports.latex",
    "bibtexcommand":"biber",
    "natbib":"--biblatex"
    },
  "springer":{
    "template_file":"templates/springer_svjour3.latex",
    "bibtexcommand":"bibtex",
    "natbib":"--natbib"
    }
  }
